//
//  LoginPresenter.swift
//  Login
//
//  Created by Christian Adiputra on 08/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginPresenter {

    // MARK: - Private properties -

    private unowned let view: LoginViewInterface
    private let interactor: LoginInteractorInterface
    private let wireframe: LoginWireframeInterface
    var email: String?
    var password: String?

    // MARK: - Lifecycle -

    init(
        view: LoginViewInterface,
        interactor: LoginInteractorInterface,
        wireframe: LoginWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {

    func login() {
        guard let email = email, let password = password else { return }
        interactor.login(email: email, password: password)
    }
    
    func setEmail(email: String) {
        self.email = email
    }
    
    func setPass(pass: String) {
        self.password = pass
    }
    
}

extension LoginPresenter: LoginInteractorOutputInterface {
    func didSuccessLogin() {
        wireframe.goToHome()
    }
    
    
}
