//
//  LoginInteractor.swift
//  Login
//
//  Created by Christian Adiputra on 08/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import NetworkKit

final class LoginInteractor {
    weak var presenter: LoginInteractorOutputInterface?
    let authService: AuthServiceProtocol = AuthService()
    
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    func login(email: String, password: String) {
        authService.login(name: email, pass: password) { [weak self] response in
            self?.presenter?.didSuccessLogin()
        } onFailure: { [weak self] error in
            print("error \(error.localizedDescription)")
        }

    }
    
}
