//
//  LoginInterfaces.swift
//  Login
//
//  Created by Christian Adiputra on 08/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

protocol LoginWireframeInterface: WireframeInterface {
    func goToHome()
}

protocol LoginViewInterface: ViewInterface {
    
}

protocol LoginPresenterInterface: PresenterInterface {
    var email: String? {
        get
    }
    var password: String? {
        get
    }
    func login()
    func setEmail(email: String)
    func setPass(pass: String)
}

protocol LoginInteractorInterface: InteractorInterface {
    func login(email: String, password: String)
}

protocol LoginInteractorOutputInterface: InteractorOutputInterface {
    func didSuccessLogin()
}
